### ISSUE TITLE
How to filter parameters in logs ?

### ISSUE THREAD

**Issue by sofianegargouri** [boltops-tools/jets#399]
Hi ! 

Is it possible to filter parameters in logs as Rails is actually doing. 
We tried to add `Jets.application.config.filter_parameters += [:password, :password_confirmation]` in an initializer, without any success.

Thanks for your help, and keep up the good work !

**Comment by tongueroo** [comment]
Not currently. Will consider PRs for this

**Comment by josediaz16** [comment]
I've had fun working with Jets. I think I can work on this 😄 , I'd like to contribute.
