### ISSUE TITLE
Deployment failed to create DomainName 

### ISSUE THREAD

**Issue by vnorguet** [boltops-tools/jets#405]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |   OSX 10.14.6 (18G1012)      |
| Jets             |    2.3.5     |
| Ruby             |     2.5.3    |

---

## Expected Behaviour

After deployment, my service is accessible myapp.mydomain.com

## Current Behavior

Deployment fails because it cannot create the domain

## Step-by-step reproduction instructions

1. Configure the service
  1. Create custom domain on Route53
  2. Create certificate on AWS ACM
  3.  `application.rb`
```ruby
Jets.application.configure do
  # ....
  config.domain.route53 = true
  config.domain.name = 'myapp'
  config.domain.hosted_zone_name = "mydomain.com."
  config.domain.cert_arn = "arn:aws:acm:us-east-1:1111111:certificate/certificate-id"
  config.domain.endpoint_type = "EDGE"
end
```

2. Run `jets deploy`

Logs here: https://gist.github.com/vnorguet/0268b8e7fde2f3b817c2ab7468d0c5f3

## Solution Suggestion

Comment `config.domain.hosted_zone_name`, and the deployment is successfull.

Note: I deploy in the zone: eu-west-1, and the certificate is in us-east-1 zone

**Comment by tongueroo** [comment]
Used custom domains recently and it worked. Unsure what’s going on here. Wondering what the nested child stack error said. Here’s how you find it https://rubyonjets.com/docs/debugging/cloudformation/
