### ISSUE TITLE
Ruby 2.7 Support 

### ISSUE THREAD

**Issue by tongueroo** [boltops-tools/jets#444]
## Summary

Exciting News: AWS Lambda released support for 2.7 🎉 
https://aws.amazon.com/about-aws/whats-new/2020/02/aws-lambda-supports-ruby-2-7/

## Motivation

It’s the latest version of Ruby. Now it’s officially supported. 

## Guide-level explanation

Allow users to set Runtime version. 

## Unresolved Questions

https://community.rubyonjets.com/t/could-not-find-rake-13-0-1-in-any-of-the-sources/398

**Comment by davelooi** [comment]
Is there any estimated delivery for this? Anyway I can help?

**Comment by theooos** [comment]
What's the latest on this? Would be happy to get involved :)

**Comment by tongueroo** [comment]
Dug into this a while back. Most of the effort will be a Custom Lambda Layer that works with new Ruby 2.7 Lambda Runtime. If anyone wants to take a close, that's cool. No sweat either way of course 👍

It looks like the new Lambda runtime uses a stripped-down version of the Amazon Linux 2 AMI. Common shared libraries, which many gems rely on, are also not installed. This causes issues with common gems like nokogiri.

Note, this issue is at the top of the list. It'll take some time, though.

**Comment by choilive** [comment]
With the recent announcement of Container Image Support, this might be much easier to support.
https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/

**Comment by farjadfazli** [comment]
Hi @tongueroo, just wanted to know if there is any update on this? We are starting a new project and have to decide on a ruby version. Thank you!

**Comment by tongueroo** [comment]
Have starting looking at this recently again, but no update and no time frame quite yet. This is still the highest priority though.

**Comment by farjadfazli** [comment]
Ok got it, thanks for the quick response and really appreciate all your work!

**Comment by sam0x17** [comment]
imo the container image direction might be an easier one if the performance is the same (which I assume it is)

**Comment by edjames** [comment]
Hello, just in case anyone missed it... the Ruby 2.5 Lambda runtime base AMI reached end of life on December 31, 2020 (i.e. Amazon Linux 1). The unfortunately make it quite tricky to compile compatible resources/binaries manually to be used within the Jets context.

I'm happy to help our moving towards support for Ruby 2.7 where I can, so please just ask and I'll do my best. I love this project so would be happy to be involved.

**Comment by tongueroo** [comment]
Handled in #522
