### ISSUE TITLE
Why install Bootstrap4 beta?

### ISSUE THREAD

**Issue by rhiroe** [boltops-tools/jets#453]
Hi, thanks for developing a great library.

```bash
$ jets new app_name --bootstrap
```

I expected the latest version of Bootstrap would be installed.
However, Bootstrap 4 beta is installed.

https://github.com/tongueroo/jets/blob/ed62c3c5da3bc68e5711efa7092fc838ab18c252/lib/jets/commands/new.rb#L109

Does it make sense to dare install the beta version?

I think `jets new --bootstrap` should to install the latest version.
Can I make a pull request for this?

Thanks.

**Comment by tongueroo** [comment]
Feel like there was a reason I used bootstrap beta. Think the time, crud.js wouldn’t work without beta and requiring the additional js packages. The js world sometimes moves fast like that. 🤦🏻‍♂️ Think it’s fine to remove beta but crud.js would need to be tested. 👌

**Comment by timlawrenz** [comment]
@rhiroe did you have a chance to look at this? How would crud.js be tested?

**Comment by rhiroe** [comment]
@timlawrenz sorry, I forgot.
I'm stuck because I don't know how to test crud.js.

**Comment by tongueroo** [comment]
Handled in #522
