### ISSUE TITLE
`jets new demo` requires "rake-13.0.1"

### ISSUE THREAD

**Issue by bigwheel** [boltops-tools/jets#485]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |    macOS Mojave (10.14.5)     |
| Jets             |  2.3.16       |
| Ruby             |    ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-darwin18] (rbenv)     |

---

## Expected Behaviour

Success of `jets new demo`

## Current Behavior

Fails on the way.

Detail: [jets\_new\_log](https://gist.github.com/bigwheel/b8785f36c0470179f17355ee0d4980ba)

## Step-by-step reproduction instructions

I do just [Quick Start \- Jets Ruby Serverless Framework](https://rubyonjets.com/quick-start/).

1. By a MacBook Pro A1990
2. Install rbenv
3. Install ruby 2.5.8 by rbenv
4. Restart Shell
5. Install jets
6. Restart Shell
7. `jets new demo`

## Code Sample

`jets new demo`

## Solution Suggestion

This may be a matter of dependency declaration.

**Comment by bigwheel** [comment]
Im understanding why this happens.

```
$% cat ~/.bundle/config
---
BUNDLE_PATH: "vendor/bundle"
```

https://github.com/tongueroo/jets/blob/0df7fc93/lib/jets/commands/new.rb#L65-L87

`bundle install` executes with `BUNDLE_IGNORE_CONFIG`, but `bundle exec jets webpacker:install` does not.

This could be considered as my environment problem. But it seems like `BUNDLE_IGNORE_CONFIG` inconsistency problem.

**Comment by johnreitano** [comment]
I hit this same issue. I worked around the issue by temporarily commenting out the contents of ~/.bundle/config .

**Comment by bigwheel** [comment]
Me too.

**Comment by chase439** [comment]
Thank you for the hints, as I was using Cloud9, I had to remove my personal `~/.bundle/config`, install and use Ruby 2.7 and install latest bundler to get it to work.

**Comment by mathieujobin** [comment]
it could help if it was supported to add `jets` to our Gemfile

**Comment by bigwheel** [comment]
stall
