### ISSUE TITLE
Afterburner - Giving up on trying to connect to localhost:9292

### ISSUE THREAD

**Issue by sam0x17** [boltops-tools/jets#521]
In the latest version of jets, if you create a hello world Rails 5 app in Afterburner mode and deploy to lambda, you'll get:
```
Giving up on trying to connect to localhost:9292 | Giving up on trying to connect to localhost:9292
```

This been reported a few times in gitter and elsewhere
* https://gitter.im/tongueroo/jets?at=5fcfcf66fcbf697f7327edb7
* https://gitter.im/tongueroo/jets?at=5ff5f76191e9b71badbd2b28

To reproduce, simply create a Rails 5 app using Ruby 2.5.7 and try mounting it in afterburner mode and deploying to Lambda.

**Comment by tongueroo** [comment]
Bummed about this. Updated docs with a note that the experimental feature is broken: https://rubyonjets.com/docs/rails-support/ Unsure exactly when will take a closer look. It's a matter of time. Trying to take an efficient approach here. Thanks!
