### ISSUE TITLE
Deploy fail when Controller's before_action method naming has a exclamation mark

### ISSUE THREAD

**Issue by lustan3216** [boltops-tools/jets#531]
| Software         | Version |
| ---------------- | ------- |
| Operating System |    Mac 10.15    |
| Jets             |    3.02     |
| Ruby             |    2.7.2     |

---

## Expected Behaviour

I tried to deploy by `jets deploy` and expected success.

## Current Behavior

Deploy fails because of the exclamation mark in the method name.
```
UPDATE_FAILED AWS::CloudFormation::Stack HomeController Template format error: Resource name AuthenticateUserFromCognito!LambdaFunction is non alphanumeric.
```

## Code Sample

ApplicationController.rb
```
class ApplicationController < Jets::Controller::Base
  def authenticate_user_from_cognito!
    render json: { data: 'No authorized' } unless authorized_username
  end
end

```

MesController.rb
```
class MesController < Jets::Controller::Base
  before_action :authenticate_user_from_cognito!
end

```

HomeController.rb
```
class HomeController < Jets::Controller::Base  
end

```

When deploying, it will break on the controller I didn't use authenticate_user_from_cognito!

**Comment by tongueroo** [comment]
Dup of #520
