### ISSUE TITLE
Should be possible to deploy without postgres or mysql

### ISSUE THREAD

**Issue by jagthedrummer** [boltops-tools/jets#533]
## Summary

Currently it seems like jets expects either `pg` or `mysql2` to be installed and properly configured. I've tried removing them both from the `Gemfile` but then jets seems to be unable to run basic commands.

## Motivation

If I'm using DynamoDB I shouldn't need to have postgres/mysqle gems installed and configured.

## Guide-level explanation

```
jets new demo-without-database --database=false
```

## Reference-level explanation

??

## Drawbacks

??

## Unresolved Questions

Is there currently a way to do this that I'm missing?

**Comment by SteffanPerry** [comment]
can not repo with 3.0.7:

```
jets new demo-without-database --no-database
jets deploy
...
=> API Gateway Endpoint: https://filtered.execute-api.us-east-1.amazonaws.com/dev/
```

Be sure to use `--no-database` not `--database=false`
