### ISSUE TITLE
Incompatible dependency license

### ISSUE THREAD

**Issue by jas14** [boltops-tools/jets#535]
## Summary

Dependency `mimemagic` was previously licensed under the MIT License, but had to change to GPL this morning. All versions under MIT have been yanked, and GPL is incompatible with Jets MIT license. See https://github.com/minad/mimemagic/issues/97.

## Recommendations

I suggest that the `mimemagic` dependency be replaced with `mini_mime`.

`mimemagic` appears to be used only in `lib/jets/internal/app/controllers/jets/public_controller.rb`, which calls `MimeMagic.by_path` (which infers a file's MIME type from its extension). [`mini_mime`](https://github.com/discourse/mini_mime) does similar inference, but it is licensed under the MIT License.

**Comment by tongueroo** [comment]
Released in v3.0.3
