### ISSUE TITLE
Jets does not support multiple value response headers

### ISSUE THREAD

**Issue by SteffanPerry** [boltops-tools/jets#555]
## Checklist

- [ x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x ] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [ ] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |OSX 10.15.7|
| Jets             | 3.0.5|
| Ruby             |2.7.2|

---

## Expected Behaviour

Setting response headers with multiple values should create a seperate response header for each value.

## Current Behavior

Currently, settings a header to multiple values results in a single response header containing all values.

## Step-by-step reproduction instructions

Create a multi-value header and deploy to staging. 

Note: This issue does not occur locally using  puma 

`set_header('Set-Cookie', ['cookie_a=a', 'cookie_b=b'])`

## Solution Suggestion

Use API gateways"multiValueHeaders" field when rendering a response.

**Comment by SteffanPerry** [comment]
I will have a PR for this issue shortly.

**Comment by tongueroo** [comment]
Fixed in #556
