### ISSUE TITLE
support zeitwerk 2.5.x

### ISSUE THREAD

**Issue by tongueroo** [boltops-tools/jets#601]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [ ] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System | Cloud9 |
| Jets             | 3.0.18 |
| Ruby             | 2.7.4 |

---

## Expected Behaviour

Jets to load with zeitwerk 2.5.x.

## Current Behavior

Jets does not load with zeitwerk 2.5.x.

## Step-by-step reproduction instructions

Install latest version of zeitwerk (2.5.0) https://github.com/fxn/zeitwerk/blob/main/CHANGELOG.md

    gem list zeitwerk

Should show it installed.

Run a command like:

    jets server

It'll bomb loading since the `loader.preload` method has been removed. Will need to replace with `loader.setup` method.

## Code Sample

none provided.

## Solution Suggestion

Replace `loader.preload` with `loader.setup` method.

**Comment by sohey-dr** [comment]
Can I try this issue?

**Comment by tongueroo** [comment]
Go for it

**Comment by tongueroo** [comment]
Handled in #614 🎉
