### ISSUE TITLE
403 error during a deploy

### ISSUE THREAD

**Issue by oleksiivykhor** [boltops-tools/jets#633]
Hello. I'm trying to deploy a jets application with a custom layer, but getting the error below.
Does it mean that the layer is broken, or is it a bug?
Thank you.

> Checking projects gems for binary serverlessgems...
bundler: failed to load command: jets (/usr/local/bundle/bin/jets)
OpenURI::HTTPError: 403 Forbidden
  /usr/local/lib/ruby/2.7.0/open-uri.rb:387:in `open_http'
  /usr/local/lib/ruby/2.7.0/open-uri.rb:764:in `buffer_open'
  /usr/local/lib/ruby/2.7.0/open-uri.rb:235:in `block in open_loop'
  /usr/local/lib/ruby/2.7.0/open-uri.rb:233:in `catch'
  /usr/local/lib/ruby/2.7.0/open-uri.rb:233:in `open_loop'
  /usr/local/lib/ruby/2.7.0/open-uri.rb:174:in `open_uri'
  /usr/local/lib/ruby/2.7.0/open-uri.rb:744:in `open'
  /usr/local/lib/ruby/2.7.0/open-uri.rb:50:in `open'
  /usr/local/bundle/gems/serverlessgems-0.2.0/lib/jets/gems/extract/base.rb:44:in `download_file'
  /usr/local/bundle/gems/serverlessgems-0.2.0/lib/jets/gems/extract/gem.rb:55:in `download_gem'
  /usr/local/bundle/gems/serverlessgems-0.2.0/lib/jets/gems/extract/gem.rb:11:in `run'
  /usr/local/bundle/gems/jets-3.1.5/lib/jets/builders/gem_replacer.rb:22:in `block in run'
  /usr/local/bundle/gems/jets-3.1.5/lib/jets/builders/gem_replacer.rb:20:in `each'
  /usr/local/bundle/gems/jets-3.1.5/lib/jets/builders/gem_replacer.rb:20:in `run'
  /usr/local/bundle/gems/jets-3.1.5/lib/jets/builders/lambda_layer.rb:65:in `replace_compiled_gems'
  /usr/local/bundle/gems/jets-3.1.5/lib/jets/builders/lambda_layer.rb:10:in `build'
  /usr/local/bundle/gems/jets-3.1.5/lib/jets/builders/code_builder.rb:395:in `build_lambda_layer'
  /usr/local/bundle/gems/jets-3.1.5/lib/jets/builders/code_builder.rb:384:in `package_ruby'
  /usr/local/bundle/gems/jets-3.1.5/lib/jets/builders/code_builder.rb:41:in `block in build'
  /usr/local/bundle/gems/jets-3.1.5/lib/jets/builders/code_builder.rb:38:in `chdir'
  /usr/local/bundle/gems/jets-3.1.5/lib/jets/builders/code_builder.rb:38:in `build'
  /usr/local/bundle/gems/jets-3.1.5/lib/jets/commands/build.rb:27:in `build_code'
  /usr/local/bundle/gems/jets-3.1.5/lib/jets/commands/deploy.rb:61:in `build_code'
  /usr/local/bundle/gems/jets-3.1.5/lib/jets/commands/deploy.rb:32:in `run'
  /usr/local/bundle/gems/jets-3.1.5/lib/jets/commands/main.rb:27:in `deploy'
  /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
  /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
  /usr/local/bundle/gems/jets-3.1.5/lib/jets/commands/base.rb:38:in `dispatch'
  /usr/local/bundle/gems/jets-3.1.5/lib/jets/commands/base.rb:27:in `perform'
  /usr/local/bundle/gems/jets-3.1.5/lib/jets/cli.rb:28:in `start'
  /usr/local/bundle/gems/jets-3.1.5/lib/jets/cli.rb:5:in `start'
  /usr/local/bundle/gems/jets-3.1.5/exe/jets:14:in `<top (required)>'
  /usr/local/bundle/bin/jets:23:in `load'
  /usr/local/bundle/bin/jets:23:in `<top (required)>'

**Comment by ssunday** [comment]
I am having this issue as well, but without custom layers.
