### ISSUE TITLE
Ruby `3.x` support

### ISSUE THREAD

**Issue by jhunschejones** [boltops-tools/jets#636]
## Summary

Ruby `3.x` has been out [for more than 2 years now](https://www.ruby-lang.org/en/downloads/releases/), so I was surprised when I went to run `jets new` today and couldn't because there's no support for modern Ruby versions. 😞 

I understand priorities need to be balanced when maintaining a project of this size, but it feels like it's time to bump this one up the list a little if it isn't already on top 😊  Thanks for helping build and maintain this awesome library. I'm excited to see it continue to push Ruby forward in the serverless age.

**Comment by tongueroo** [comment]
Main reason Ruby 3 is not support yet is because AWS Lambda doesn’t support it yet. It’s a bummer.

> RE: Thanks for helping build and maintain this awesome library. I'm excited to see it continue to push Ruby forward in the serverless age.

Thanks for the kind words.

**Comment by jhunschejones** [comment]
> Main reason Ruby 3 is not support yet is because AWS Lambda doesn’t support it yet. It’s a bummer.
> 
> > RE: Thanks for helping build and maintain this awesome library. I'm excited to see it continue to push Ruby forward in the serverless age.
> 
> Thanks for the kind words.

Thanks for the quick response @tongueroo! Apologies, I did not realize lambda doesn't support 3.x yet 😅  Hopefully this closed issue can serve as an answer to future folks who have this same question at least. 🙏🏻

**Comment by Jengah** [comment]
Seems like this could probably be re-opened with the recent news of container base image support of Ruby 3.2 in Lambda: https://github.com/aws/aws-lambda-base-images/issues/54#issuecomment-1486974882

**Comment by tongueroo** [comment]
@Jengah Got me excited. Sadly, its only for the lambda container base image. It's not yet rolled out to AWS Lambda itself officially.  The AWS console still shows Ruby 2.7 only.

<img width="999" alt="Screenshot 2023-04-25 at 1 57 21 PM" src="https://user-images.githubusercontent.com/4085/234402407-69287c08-77b1-45e5-abb1-4ab608775357.png">

I checked 2 regions: us-east-1 and us-west-2. Seems like AWS is getting closer ready. Guessing they updated the lambda container image in preparation for it.  Will look at adding 3.2 support once it's officially released. 

Also, saw that AWS also released python 3.1 recently. So Ruby 3.2 hopefully is close 🤞

**Comment by Jengah** [comment]
Sorry for the false excitement. As the comment mentions the AWS managed framework runtime should be available within 90 days of the announcement, with 2.7 support lasting 6 months past the General Availability release of the Ruby 3.2 runtime for some roadway to get migrated.

I was more pointing out that preliminary testing _could_ be done using a the supported base container as a custom runtime, but the official managed runtime should be out in the next 60 days or so and may not be worth the effort.

**Comment by tongueroo** [comment]
Awesome. Appreciate the heads up!

**Comment by tongueroo** [comment]
Done in https://github.com/boltops-tools/jets/pull/654 🎉 Blog Post: [Jets v4 Release: Ruby 3.2 Support](https://blog.boltops.com/2023/05/27/jets-v4-release-ruby-3-2-support/)

**Comment by tongueroo** [comment]
Looks like AWS is ghost-testing Ruby 3.2 support for AWS Lambda. Ruby 3.2 does not show up in the AWS console, but you're able to deploy with the Ruby 3.2 runtime via CloudFormation. Was able to deploy a jets v4 app with ruby 3.2 successfully without the use of custom runtime. 🎉

<img width="1265" alt="aws lambda ruby 3 2" src="https://github.com/boltops-tools/jets/assets/4085/7cf047f9-c89d-495d-a42f-ebd113d623cc">
