### ISSUE TITLE
 NoMethodError: undefined method `host' for nil:NilClass when sending mail locally

### ISSUE THREAD

**Issue by jeremiahlukus** [boltops-tools/jets#664]
## Checklist

- [ ] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [ x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com
- [x ] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |         |
| Jets             |         |
| Ruby             |         |

---

## Expected Behaviour
When setting ` config.action_mailer.default_url_options = { host: 'localhost', port: 3000, protocol: "https" }` mail to be sent.

## Current Behavior
Setting host to local host then calling ` mail to: @user` triggers the rails overrides 
https://github.com/boltops-tools/jets/blob/master/lib/jets/overrides/rails/common_methods.rb#L5
the request.host is nil. 

If this issue is fixed on v5 then let me know else ill look into it and send a PR 

```
    6: 
 => 7:   binding.pry
    8:   mail to: @user
    9: end

[1] pry(#<ReviseAuth::Mailer>)> mail to: @user
========================

http://127.0.0.1:8888/profile/email?confirmation_token=eyJfcmFpbHMiOnsibWVzc2FnZSI6Ik1RPT0iLCJleHAiOiIyMDIzLTA5LTE0VDE4OjQxOjU0LjAyNVoiLCJwdXIiOiJ1c2VyL2VtYWlsX3ZlcmlmaWNhdGlvbiJ9fQ==--41e679ecbc0d545225d0838cd6c1b475b0a336797a5dee1e180c9750b9c2e49f
ActionView::Template::Error: undefined method `host' for nil:NilClass
from /Users/jeremiah.parrack/freelance/jets/lib/jets/overrides/rails/common_methods.rb:8:in `add_stage_name'
Caused by NoMethodError: undefined method `host' for nil:NilClass
```
I put some logging in jets 

```
  def add_stage_name(url)
    puts "========================"
    puts request
    puts url 
    puts request.host
    puts url 
    puts "========================"
    Jets::Controller::Stage.add(request.host, url)
  end 
  ```
  you can see url is present but request is nil i think this is because its a background job

**Comment by tongueroo** [comment]
Took a look the jets v5 branch. It's a bug on both.

**Comment by jeremiahlukus** [comment]
I’ll pick it up and send a PR soon.
