### ISSUE TITLE
Add `--css tailwind` flag to jets cli

### ISSUE THREAD

**Issue by jeremiahlukus** [boltops-tools/jets#666]
## Summary
Currently with rails you can type `rails new my-project --css tailwind` I would like to be able to duplicate this for jets.
If this is a feature you are ok with I can add this after you merge in v5 to avoid conflicts since its not urgent. 

I added a quick how to in the jets support form in case someone searches tailwind 
https://community.boltops.com/t/how-to-add-tailwind-css/1089

## Motivation
Easily add styling to jets.

**Comment by tongueroo** [comment]
Sure. Tailwind would be cool.

Ok to add to current master. Unsure how long v5 may take so just add to main and will figure out the conflicts to resolve.

**Comment by jeremiahlukus** [comment]
Ok will start tomorrow.

**Comment by tongueroo** [comment]
Yes. In jets v5, the default is importmaps and while webpacker will be around it'll be remove eventually like Rails.
