### ISSUE TITLE
Afterburner mode with Ruby 3.2.0

### ISSUE THREAD

**Issue by djolereject** [boltops-tools/jets#672]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com
- [ ] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |  macOS 14.0       |
| Jets             |    4.0.7     |
| Ruby             |     3.2.0    |

---

## Expected Behaviour
I have an existing Rails app where I created `.jets/project/.env` file with `DATABASE_URL` value in it.
`jets deploy` command should bundle Rails app to Jets and deploy it.

## Current Behavior
When I run `jets deploy` in the root of the app, everything seems normal until it crashes trying to install `pg` gem with version `0.21.0`.

## Step-by-step reproduction instructions

When command `=> cd /tmp/jets/scrape-commander/cache && env bundle install` starts, it gets to installing `pg` gem, but for some reason version `0.21.0`, which is incompatible with `Ruby 3.2.0`. I'm not sure where is defined to get this version, especially since my Gemfile is locking `pg` gem to `1.5.4`.

<details>
 <summary>These are the logs if someone finds them helpful:</summary>
$ jets deploy

=> Rails app detected: Enabling Jets Afterburner to deploy to AWS Lambda.
Deploying to Lambda scrape-commander-dev environment...
The /tmp/jets/scrape-commander/cache folder exists. Incrementally re-building the jets using the cache.  To clear the cache: rm -rf /tmp/jets/scrape-commander/cache
=> Compling assets in current project directory
=> cd /tmp/jets/turbo-wrapper-project && bundle install
Using rake 13.0.6
Using concurrent-ruby 1.2.2
Using i18n 1.14.1
Using minitest 5.20.0
Using tzinfo 2.0.6
Using activesupport 7.0.8
Using builder 3.2.4
Using erubi 1.12.0
Using racc 1.7.1
Using nokogiri 1.15.4 (arm64-darwin)
Using rails-dom-testing 2.2.0
Using crass 1.0.6
Using loofah 2.21.3
Using rails-html-sanitizer 1.6.0
Using actionview 7.0.8
Using rack 2.2.8
Using rack-test 2.1.0
Using actionpack 7.0.8
Using nio4r 2.5.9
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.6
Using actioncable 7.0.8
Using globalid 1.2.1
Using activejob 7.0.8
Using activemodel 7.0.8
Using activerecord 7.0.8
Using marcel 1.0.2
Using mini_mime 1.1.5
Using activestorage 7.0.8
Using date 3.3.3
Using timeout 0.4.0
Using net-protocol 0.2.1
Using net-imap 0.3.7
Using net-pop 0.1.2
Using net-smtp 0.4.0
Using mail 2.8.1
Using actionmailbox 7.0.8
Using actionmailer 7.0.8
Using actiontext 7.0.8
Using ruby2_keywords 0.0.5
Using arbre 1.6.0
Using formtastic 4.0.0
Using formtastic_i18n 0.7.0
Using has_scope 0.8.1
Using method_source 1.0.0
Using thor 1.2.2
Using zeitwerk 2.6.12
Using railties 7.0.8
Using responders 3.1.0
Using inherited_resources 1.13.1
Using jquery-rails 4.6.0
Using kaminari-core 1.2.2
Using kaminari-actionview 1.2.2
Using kaminari-activerecord 1.2.2
Using kaminari 1.2.2
Using ransack 4.0.0
Using activeadmin 3.0.0
Using public_suffix 5.0.3
Using addressable 2.8.5
Using bcrypt 3.1.19
Using bindex 0.8.1
Using msgpack 1.7.2
Using bootsnap 1.16.0
Using bundler 2.3.26
Using matrix 0.4.2
Using regexp_parser 2.8.1
Using xpath 3.2.0
Using capybara 3.39.2
Using coderay 1.1.3
Using orm_adapter 0.5.0
Using warden 1.2.9
Using devise 4.9.2
Using diff-lcs 1.5.0
Using dry-core 1.0.1
Using dry-monads 1.6.0
Using factory_bot 6.2.1
Using factory_bot_rails 6.2.0
Using faker 3.2.1
Using ffi 1.16.2
Using multi_xml 0.6.0
Using httparty 0.21.0
Using importmap-rails 1.2.1
Using pg 1.5.4
Using pry 0.14.2
Using pry-rails 0.3.9
Using puma 5.6.7
Using rails 7.0.8
Using redis 4.8.1
Using rexml 3.2.6
Using rspec-support 3.12.1
Using rspec-core 3.12.2
Using rspec-expectations 3.12.3
Using rspec-mocks 3.12.6
Using rspec-rails 6.0.3
Using rubyzip 2.3.2
Using sassc 2.4.0
Using sprockets 4.2.1
Using sprockets-rails 3.4.2
Using tilt 2.3.0
Using sassc-rails 2.1.2
Using websocket 1.2.10
Using selenium-webdriver 4.10.0
Using stimulus-rails 1.2.2
Using turbo-rails 1.4.0
Using web-console 4.2.1
Using webdrivers 5.3.1
Bundle complete! 22 Gemfile dependencies, 106 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
=> cd /tmp/jets/turbo-wrapper-project/rack && bundle exec rake assets:clobber --trace
** Invoke assets:clobber (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:clobber
I, [2023-10-22T07:39:50.349311 #98423]  INFO -- : Removed /private/tmp/jets/turbo-wrapper-project/rack/public/assets
=> cd /tmp/jets/turbo-wrapper-project/rack && bundle exec rake assets:precompile --trace
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:precompile
I, [2023-10-22T07:39:51.698918 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/manifest-b84bfa46a33d7f0dc4d2e7b8889486c9a957a5e40713d58f54be71b66954a1ff.js
I, [2023-10-22T07:39:51.699005 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/manifest-b84bfa46a33d7f0dc4d2e7b8889486c9a957a5e40713d58f54be71b66954a1ff.js.gz
I, [2023-10-22T07:39:51.699115 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/active_admin-9b47f6df8a93d571852c80ebe8143411c5d6a200e46f1950563155ef8df92b29.css
I, [2023-10-22T07:39:51.699191 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/active_admin-9b47f6df8a93d571852c80ebe8143411c5d6a200e46f1950563155ef8df92b29.css.gz
I, [2023-10-22T07:39:51.699337 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/application-3dd1b30b48ae1e26c2ef782dda37e3d629f5ff20d61cfbd6a192f6a3cb46391c.css
I, [2023-10-22T07:39:51.699414 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/application-3dd1b30b48ae1e26c2ef782dda37e3d629f5ff20d61cfbd6a192f6a3cb46391c.css.gz
I, [2023-10-22T07:39:51.699450 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/application-37f365cbecf1fa2810a8303f4b6571676fa1f9c56c248528bc14ddb857531b95.js
I, [2023-10-22T07:39:51.699477 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/application-37f365cbecf1fa2810a8303f4b6571676fa1f9c56c248528bc14ddb857531b95.js.gz
I, [2023-10-22T07:39:51.699549 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/controllers/application-368d98631bccbf2349e0d4f8269afb3fe9625118341966de054759d96ea86c7e.js
I, [2023-10-22T07:39:51.699584 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/controllers/application-368d98631bccbf2349e0d4f8269afb3fe9625118341966de054759d96ea86c7e.js.gz
I, [2023-10-22T07:39:51.699616 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/controllers/hello_controller-549135e8e7c683a538c3d6d517339ba470fcfb79d62f738a0a089ba41851a554.js
I, [2023-10-22T07:39:51.699640 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/controllers/hello_controller-549135e8e7c683a538c3d6d517339ba470fcfb79d62f738a0a089ba41851a554.js.gz
I, [2023-10-22T07:39:51.699674 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/controllers/index-2db729dddcc5b979110e98de4b6720f83f91a123172e87281d5a58410fc43806.js
I, [2023-10-22T07:39:51.699698 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/controllers/index-2db729dddcc5b979110e98de4b6720f83f91a123172e87281d5a58410fc43806.js.gz
I, [2023-10-22T07:39:51.699732 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/turbo-4851a9a0b1d947e810dfd0448a72aef261d455183ebea681f4f28a73640a9ece.js
I, [2023-10-22T07:39:51.699772 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/turbo-4851a9a0b1d947e810dfd0448a72aef261d455183ebea681f4f28a73640a9ece.js.gz
I, [2023-10-22T07:39:51.699820 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/turbo.min-f309baafa3ae5ad6ccee3e7362118b87678d792db8e8ab466c4fa284dd3a4700.js
I, [2023-10-22T07:39:51.699848 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/turbo.min-f309baafa3ae5ad6ccee3e7362118b87678d792db8e8ab466c4fa284dd3a4700.js.gz
I, [2023-10-22T07:39:51.699884 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/turbo.min.js-8bc8f4a58d1c106d58dec8bef6c638ff12ff4d078f19d8ebd8c4277f4c9bc85a.map
I, [2023-10-22T07:39:51.699968 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/turbo.min.js-8bc8f4a58d1c106d58dec8bef6c638ff12ff4d078f19d8ebd8c4277f4c9bc85a.map.gz
I, [2023-10-22T07:39:51.700177 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/actiontext-28c61f5197c204db043317a8f8826a87ab31495b741f854d307ca36122deefce.js
I, [2023-10-22T07:39:51.700601 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/actiontext-28c61f5197c204db043317a8f8826a87ab31495b741f854d307ca36122deefce.js.gz
I, [2023-10-22T07:39:51.700988 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/trix-1563ff9c10f74e143b3ded40a8458497eaf2f87a648a5cbbfebdb7dec3447a5e.js
I, [2023-10-22T07:39:51.701026 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/trix-1563ff9c10f74e143b3ded40a8458497eaf2f87a648a5cbbfebdb7dec3447a5e.js.gz
I, [2023-10-22T07:39:51.701724 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/trix-ac629f94e04ee467ab73298a3496a4dfa33ca26a132f624dd5475381bc27bdc8.css
I, [2023-10-22T07:39:51.702616 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/trix-ac629f94e04ee467ab73298a3496a4dfa33ca26a132f624dd5475381bc27bdc8.css.gz
I, [2023-10-22T07:39:51.702697 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/es-module-shims-69d0cb4dc1d01c9dc2ed52f2ab66874fd545fe7e35c7841009b4e8c55f231dee.js
I, [2023-10-22T07:39:51.702729 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/es-module-shims-69d0cb4dc1d01c9dc2ed52f2ab66874fd545fe7e35c7841009b4e8c55f231dee.js.gz
I, [2023-10-22T07:39:51.702762 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/es-module-shims.min-4ca9b3dd5e434131e3bb4b0c1d7dff3bfd4035672a5086deec6f73979a49be73.js
I, [2023-10-22T07:39:51.702787 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/es-module-shims.min-4ca9b3dd5e434131e3bb4b0c1d7dff3bfd4035672a5086deec6f73979a49be73.js.gz
I, [2023-10-22T07:39:51.702818 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/es-module-shims.js-c69f1a5dd068dfc08a4cedc0ad77b792985bf256e162852bd03cdf764b666c4a.map
I, [2023-10-22T07:39:51.704952 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/es-module-shims.js-c69f1a5dd068dfc08a4cedc0ad77b792985bf256e162852bd03cdf764b666c4a.map.gz
I, [2023-10-22T07:39:51.705006 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/stimulus-f75215805563870a61ee9dc5a207ce46d4675c7e667558a54344fd1e7baa697f.js
I, [2023-10-22T07:39:51.705033 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/stimulus-f75215805563870a61ee9dc5a207ce46d4675c7e667558a54344fd1e7baa697f.js.gz
I, [2023-10-22T07:39:51.705065 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/stimulus-autoloader-c584942b568ba74879da31c7c3d51366737bacaf6fbae659383c0a5653685693.js
I, [2023-10-22T07:39:51.705505 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/stimulus-autoloader-c584942b568ba74879da31c7c3d51366737bacaf6fbae659383c0a5653685693.js.gz
I, [2023-10-22T07:39:51.705579 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/stimulus-importmap-autoloader-db2076c783bf2dbee1226e2add52fef290b5d31b5bcd1edd999ac8a6dd31c44a.js
I, [2023-10-22T07:39:51.705621 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/stimulus-importmap-autoloader-db2076c783bf2dbee1226e2add52fef290b5d31b5bcd1edd999ac8a6dd31c44a.js.gz
I, [2023-10-22T07:39:51.705657 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/stimulus-loading-3576ce92b149ad5d6959438c6f291e2426c86df3b874c525b30faad51b0d96b3.js
I, [2023-10-22T07:39:51.705921 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/stimulus-loading-3576ce92b149ad5d6959438c6f291e2426c86df3b874c525b30faad51b0d96b3.js.gz
I, [2023-10-22T07:39:51.706071 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/stimulus.min-dd364f16ec9504dfb72672295637a1c8838773b01c0b441bd41008124c407894.js
I, [2023-10-22T07:39:51.706120 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/stimulus.min-dd364f16ec9504dfb72672295637a1c8838773b01c0b441bd41008124c407894.js.gz
I, [2023-10-22T07:39:51.706222 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/stimulus-autoloader-c584942b568ba74879da31c7c3d51366737bacaf6fbae659383c0a5653685693.js
I, [2023-10-22T07:39:51.706627 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/stimulus-autoloader-c584942b568ba74879da31c7c3d51366737bacaf6fbae659383c0a5653685693.js.gz
I, [2023-10-22T07:39:51.706685 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/stimulus-importmap-autoloader-db2076c783bf2dbee1226e2add52fef290b5d31b5bcd1edd999ac8a6dd31c44a.js.gz
I, [2023-10-22T07:39:51.707067 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/stimulus-loading-3576ce92b149ad5d6959438c6f291e2426c86df3b874c525b30faad51b0d96b3.js.gz
I, [2023-10-22T07:39:51.707151 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/stimulus.min.js-2cc63625fa177963b45da974806e7aee846cbf1d4930815733d0fdf3fb232325.map
I, [2023-10-22T07:39:51.707185 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/stimulus.min.js-2cc63625fa177963b45da974806e7aee846cbf1d4930815733d0fdf3fb232325.map.gz
I, [2023-10-22T07:39:51.707253 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/active_admin-3fed59889f98b6769d4d7400d5854bb95491995ebd71e340c415e378a9ec34dc.js
I, [2023-10-22T07:39:51.707278 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/active_admin-3fed59889f98b6769d4d7400d5854bb95491995ebd71e340c415e378a9ec34dc.js.gz
I, [2023-10-22T07:39:51.707400 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/activestorage-3ab61e47dd4ee2d79db525ade1dca2ede0ea2b7371fe587e408ee37b7ade265d.js
I, [2023-10-22T07:39:51.707433 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/activestorage-3ab61e47dd4ee2d79db525ade1dca2ede0ea2b7371fe587e408ee37b7ade265d.js.gz
I, [2023-10-22T07:39:51.708299 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/activestorage.esm-01f58a45d77495cdfbdfcc872902a430426c4391634ec9c3da5f69fbf8418492.js
I, [2023-10-22T07:39:51.710663 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/activestorage.esm-01f58a45d77495cdfbdfcc872902a430426c4391634ec9c3da5f69fbf8418492.js.gz
I, [2023-10-22T07:39:51.710829 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/actioncable-5433453f9b6619a9de91aaab2d7fc7ff183e5260c0107cbc9a1aa0c838d9a74e.js
I, [2023-10-22T07:39:51.710863 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/actioncable-5433453f9b6619a9de91aaab2d7fc7ff183e5260c0107cbc9a1aa0c838d9a74e.js.gz
I, [2023-10-22T07:39:51.710896 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/actioncable.esm-e01089c3ec4fe7817fa9abcad06cab6bdc387f95f0ca6aab4bf7ba7537f70690.js
I, [2023-10-22T07:39:51.710922 #98427]  INFO -- : Writing /private/tmp/jets/turbo-wrapper-project/rack/public/assets/actioncable.esm-e01089c3ec4fe7817fa9abcad06cab6bdc387f95f0ca6aab4bf7ba7537f70690.js.gz
=> Copying current project directory to temporary build area: /tmp/jets/scrape-commander/stage/code
=> Reconfiguring webpacker development settings for AWS Lambda.
=> Bundling: running bundle install in cache area: /tmp/jets/scrape-commander/cache.
=> cd /tmp/jets/scrape-commander/cache && env bundle install
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Installing pg 0.21.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /private/tmp/jets/scrape-commander/cache/vendor/gems/ruby/3.2.0/gems/pg-0.21.0/ext
/Users/djole/.rbenv/versions/3.2.0/bin/ruby extconf.rb
checking for pg_config... yes
Using config values from /Applications/Postgres.app/Contents/Versions/latest/bin/pg_config
checking for libpq-fe.h... yes
checking for libpq/libpq-fs.h... yes
checking for pg_config_manual.h... yes
checking for PQconnectdb() in -lpq... yes
checking for PQconnectionUsedPassword()... yes
checking for PQisthreadsafe()... yes
checking for PQprepare()... yes
checking for PQexecParams()... yes
checking for PQescapeString()... yes
checking for PQescapeStringConn()... yes
checking for PQescapeLiteral()... yes
checking for PQescapeIdentifier()... yes
checking for PQgetCancel()... yes
checking for lo_create()... yes
checking for pg_encoding_to_char()... yes
checking for pg_char_to_encoding()... yes
checking for PQsetClientEncoding()... yes
checking for PQlibVersion()... yes
checking for PQping()... yes
checking for PQsetSingleRowMode()... yes
checking for PQconninfo()... yes
checking for PQsslAttribute()... yes
checking for rb_encdb_alias()... yes
checking for rb_enc_alias()... yes
checking for rb_thread_call_without_gvl()... yes
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_fd_select()... yes
checking for rb_w32_wrap_io_handle()... no
checking for rb_str_modify_expand()... yes
checking for rb_hash_dup()... yes
checking for PGRES_COPY_BOTH in libpq-fe.h... yes
checking for PGRES_SINGLE_TUPLE in libpq-fe.h... yes
checking for PG_DIAG_TABLE_NAME in libpq-fe.h... yes
checking for struct pgNotify.extra in libpq-fe.h... yes
checking for unistd.h... yes
checking for inttypes.h... yes
checking for ruby/st.h... yes
checking for C99 variable length arrays... yes
creating extconf.h
creating Makefile

current directory: /private/tmp/jets/scrape-commander/cache/vendor/gems/ruby/3.2.0/gems/pg-0.21.0/ext
make DESTDIR\= sitearchdir\=./.gem.20231022-98432-yic7si sitelibdir\=./.gem.20231022-98432-yic7si clean

current directory: /private/tmp/jets/scrape-commander/cache/vendor/gems/ruby/3.2.0/gems/pg-0.21.0/ext
make DESTDIR\= sitearchdir\=./.gem.20231022-98432-yic7si sitelibdir\=./.gem.20231022-98432-yic7si
compiling gvl_wrappers.c
In file included from gvl_wrappers.c:6:
In file included from ./pg.h:132:
/Applications/Postgres.app/Contents/Versions/15/include/pg_config_manual.h:85:5: warning: 'SIZEOF_VOID_P' is not defined, evaluates to 0 [-Wundef]
#if SIZEOF_VOID_P >= 8
    ^
/Applications/Postgres.app/Contents/Versions/15/include/pg_config_manual.h:168:5: warning: 'HAVE_DECL_POSIX_FADVISE' is not defined, evaluates to 0 [-Wundef]
#if HAVE_DECL_POSIX_FADVISE && defined(HAVE_POSIX_FADVISE)
    ^
2 warnings generated.
compiling pg.c
In file included from pg.c:49:
In file included from ./pg.h:132:
/Applications/Postgres.app/Contents/Versions/15/include/pg_config_manual.h:85:5: warning: 'SIZEOF_VOID_P' is not defined, evaluates to 0 [-Wundef]
#if SIZEOF_VOID_P >= 8
    ^
/Applications/Postgres.app/Contents/Versions/15/include/pg_config_manual.h:168:5: warning: 'HAVE_DECL_POSIX_FADVISE' is not defined, evaluates to 0 [-Wundef]
#if HAVE_DECL_POSIX_FADVISE && defined(HAVE_POSIX_FADVISE)
    ^
2 warnings generated.
compiling pg_binary_decoder.c
In file included from pg_binary_decoder.c:7:
In file included from ./pg.h:132:
/Applications/Postgres.app/Contents/Versions/15/include/pg_config_manual.h:85:5: warning: 'SIZEOF_VOID_P' is not defined, evaluates to 0 [-Wundef]
#if SIZEOF_VOID_P >= 8
    ^
/Applications/Postgres.app/Contents/Versions/15/include/pg_config_manual.h:168:5: warning: 'HAVE_DECL_POSIX_FADVISE' is not defined, evaluates to 0 [-Wundef]
#if HAVE_DECL_POSIX_FADVISE && defined(HAVE_POSIX_FADVISE)
    ^
pg_binary_decoder.c:97:8: error: call to undeclared function 'rb_tainted_str_new'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        ret = rb_tainted_str_new( val, len );
              ^
pg_binary_decoder.c:115:20: error: call to undeclared function 'rb_tainted_str_new'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        VALUE out_value = rb_tainted_str_new(NULL, encoded_len);
                          ^
2 warnings and 2 errors generated.
make: *** [pg_binary_decoder.o] Error 1

make failed, exit code 2

Gem files will remain installed in /private/tmp/jets/scrape-commander/cache/vendor/gems/ruby/3.2.0/gems/pg-0.21.0 for inspection.
Results logged to /private/tmp/jets/scrape-commander/cache/vendor/gems/ruby/3.2.0/extensions/arm64-darwin-22/3.2.0/pg-0.21.0/gem_make.out

  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:118:in `run'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:52:in `block in make'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:44:in `each'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:44:in `make'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:41:in `build'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:186:in `build_extension'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:220:in `block in build_extensions'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:217:in `each'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:217:in `build_extensions'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/installer.rb:845:in `build_extensions'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/source/rubygems.rb:202:in `install'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/installer/parallel_installer.rb:156:in `do_install'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/worker.rb:62:in `apply_func'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/worker.rb:57:in `block in process_queue'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/worker.rb:54:in `loop'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/worker.rb:54:in `process_queue'
  /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.17/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing pg (0.21.0), and Bundler cannot continue.

In Gemfile:
  jets was resolved to 0.8.12, which depends on
    pg
cd /tmp/jets/scrape-commander/cache && env bundle install failed to run.
/Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/jets-4.0.7/lib/jets/builders/ruby_packager.rb:66:in `block in bundle_install'
[7:40:01] djole:scrape_commander git:(jets*) $ gem jets -v
ERROR:  While executing gem ... (Gem::UnknownCommandError)
    Unknown command jets
	/Users/djole/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:205:in `find_command'
	/Users/djole/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:250:in `invoke_command'
	/Users/djole/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:192:in `process_args'
	/Users/djole/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:150:in `run'
	/Users/djole/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/gem_runner.rb:51:in `run'
	/Users/djole/.rbenv/versions/3.2.0/bin/gem:10:in `<main>'
</details>

**Comment by jeremiahlukus** [comment]
Anyway you can update your PG gem? `0.21.0` is a very old version the newest version is `1.5.4` . I don't think that version of PG supports ruby 3.2.

**Comment by djolereject** [comment]
> Anyway you can update your PG gem? `0.21.0` is a very old version the newest version is `1.5.4` . I don't think that version of PG supports ruby 3.2.

I would love to but my installed gem is `1.5.4`:
```
gem list pg

*** LOCAL GEMS ***

pg (1.5.4, 1.5.3)
```
I'm not sure where from is Jets getting `0.21.0`, but in the same directory when I run `jets deploy` I'm getting previously mentioned error. As for the jets version:

```
gem list jets

*** LOCAL GEMS ***

jets (4.0.7, 4.0.1)
jets-html-sanitizer (1.0.4)
```

**Comment by jeremiahlukus** [comment]
In the docs its says 
```
Update 5/3/2021: Rails experimental support is currently broken. Instead of investing time to fixing this experiment, will consider leveraging container image support which is a better approach.
```

https://rubyonjets.com/docs/rails/afterburner/


To be honest, it would be better to create a new jets app then just copy code over. I would also do this in features instead of copy/pasting everything at once since there are a couple differences.  With jets v5 around the corner i think there will be much fewer differences.

**Comment by djolereject** [comment]
I would love to, but there is Rails app already created and I was hoping of just redeploying it to AWS in this way. Thanks anyway... 
P. S. Maybe you know something about when do we expect v5?

**Comment by jeremiahlukus** [comment]
I get it, definitely a fun PR though haha. Once I run out of things I might pick this up. v5 should be ready in the next month or 2. This fixes a lot of issues and ports over devise. Which means a lot of Rails functionality is added to Jets (which should make doing afterburner mode easier)

**Comment by djolereject** [comment]
Thanks for your help and good luck with the new release!

**Comment by jeremiahlukus** [comment]
Ill ping you when i get it working 👍
